python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 0 1
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 0 2
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 0 3
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 0 4
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 0 5
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 0 6
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 0 7
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 0 8
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 0 9

python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 1 0
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 1 2
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 1 3
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 1 4
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 1 5
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 1 6
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 1 7
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 1 8
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 1 9

python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 2 1
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 2 0
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 2 3
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 2 4
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 2 5
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 2 6
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 2 7
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 2 8
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 2 9

python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 3 1
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 3 2
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 3 0
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 3 4
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 3 5
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 3 6
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 3 7
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 3 8
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 3 9

python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 4 1
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 4 2
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 4 3
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 4 0
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 4 5
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 4 6
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 4 7
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 4 8
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 4 9

python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 5 1
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 5 2
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 5 3
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 5 4
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 5 0
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 5 6
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 5 7
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 5 8
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 5 9

python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 6 1
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 6 2
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 6 3
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 6 4
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 6 5
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 6 0
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 6 7
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 6 8
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 6 9

python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 7 1
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 7 2
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 7 3
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 7 4
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 7 5
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 7 6
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 7 0
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 7 8
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 7 9

python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 8 1
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 8 2
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 8 3
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 8 4
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 8 5
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 8 6
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 8 7
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 8 0
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 8 9

python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 9 1
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 9 2
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 9 3
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 9 4
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 9 5
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 9 6
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 9 7
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 9 8
python /content/gdrive/MyDrive/MIT/9.66/assemblies_mnist_demo/mnist_raw_data_recur_in.py 9 0